# use C-a instead of C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# vi is good
setw -g mode-keys vi

set -g status off
set-option -g default-terminal "alacritty"

# vim-like splits and navigation
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-environment -g NVIM_LISTEN_ADDRESS /tmp/nvimsocket
